import java.util.Map;
import java.util.LinkedHashMap;

public class PickDepartment {

	public static Map <String, String> dept () throws Exception {

		Map <String, String> departments = new LinkedHashMap <String, String>();

		departments.put("RGOA", "Aeronautics and Astronautics");
		departments.put("QNFH","African and African American Studies");
		departments.put("QJVU","Center for African Studies");
		departments.put("QRIZ","American Studies");
		departments.put("PUZO","Anthropology");
		departments.put("QAGT","Applied Physics");
		departments.put("JMZW","Art and Architecture Library");
		departments.put("PDFJ","Art & Art History");
		departments.put("QLQX","Asian American Studies");
		departments.put("POWL","Department of East Asian Languages and Cultures");
		departments.put("LAAA","Department of Athletics, Physical Education and Recreation");
		departments.put("RBSA","Bioengineering");
		departments.put("QANB","Biology Department");
    departments.put("QAUF","Biology Department");
    departments.put("QAZR","Biology Department");
    departments.put("QQOU","Biology Department");
		departments.put("JQGI","Biology Library");
		departments.put("QIAR","BioPhysics");
		departments.put("QKLD","Buddhist Studies");
		departments.put("PKMU","Iris and B. Gerald Cantor Center for the Visual Arts");
		departments.put("ZZSQ","Carnegie Institution");
		departments.put("MNOP","Center for Advanced Study in the Behavioral Sciences");
		departments.put("QOGF","Center for Russian, East European, and Eurasian Studies");
		departments.put("MLTQ","Center for the Study of Language and Information");
    departments.put("MP","Center for the Study of Language and Information");
    departments.put("MQ","Center for the Study of Language and Information");
		departments.put("RJMA","Chemical Engineering");
    departments.put("RJ","Chemical Engineering");
		departments.put("QCAA","Chemistry");
    departments.put("QC","Chemistry");
		departments.put("JQPS","Chemistry Library");
		departments.put("RMCA","Civil and Environmental Engineering");
    departments.put("RM","Civil and Environmental Engineering");
		departments.put("PDUN","Classics");
		departments.put("PTVG","Communication");
		departments.put("PPLP","Comparative Literature");
		departments.put("QKPZ","Ctr for Comparative Studies in Race and Ethnicity");
    departments.put("QK","Ctr for Comparative Studies in Race and Ethnicity");
    departments.put("QL","Ctr for Comparative Studies in Race and Ethnicity");
    departments.put("QM","Ctr for Comparative Studies in Race and Ethnicity");
		departments.put("RSGA","Computer Science");
    departments.put("RS","Computer Science");
    departments.put("RT","Computer Science");
    departments.put("RU","Computer Science");
    departments.put("RV","Computer Science");
    departments.put("RW","Computer Science");
    departments.put("RX","Computer Science");
    departments.put("RY","Computer Science");
    departments.put("RZ","Computer Science");
		departments.put("PGKS","Creative Writing");
		departments.put("JQZC","Earth Sciences Library");
		departments.put("TDGA","Earth Systems Program");
		departments.put("QOTR","Center for East Asian Studies");
		departments.put("PVOS","Economics");
		departments.put("TFAA","Graduate School of Education");
    departments.put("TF","Graduate School of Education");
    departments.put("TG","Graduate School of Education");
    departments.put("TH","Graduate School of Education");
    departments.put("TI","Graduate School of Education");
		departments.put("SAAA","Electrical Engineering");
    departments.put("SA","Electrical Engineering");
		departments.put("TASA","Department of Energy Resources Engineering");
    departments.put("TA","Department of Energy Resources Engineering");
		departments.put("RA","School of Engineering");
    departments.put("R","School of Engineering");
    departments.put("S","School of Engineering");
		departments.put("JRIM","Engineering Library");
		departments.put("PFNZ","English");
		departments.put("QPUP","Program in Feminist, Gender, and Sexuality Studies");
		departments.put("PQAT","French and Italian");
		departments.put("NA","Freeman Spogli Institute for International Studies");
		departments.put("TCSA","Department of Geological Sciences");
    departments.put("TC","Department of Geological Sciences");
		departments.put("PQPX","German Studies");
		departments.put("JJFI","Library Collections and Services");
    departments.put("J","Library Collections and Services");
		departments.put("PGSH","History");
		departments.put("QQBI","History and Philosophy of Science");
    departments.put("QQ","History and Philosophy of Science");
		departments.put("AGBS","Hoover Institution");
    departments.put("AG","Hoover Institution");
		departments.put("QDCU","Hopkins Marine Station");
		departments.put("JRRW","Hopkins Marine Library");
		departments.put("QQOU","Human Biology");
		departments.put("NLRU","Stanford Humanities Center");
		departments.put("PRUF","Iberian and Latin American Cultures");
		departments.put("QPNA","Institute for Gender Research");
		departments.put("QRCG","Interdisciplinary Studies in Humanities");
		departments.put("QTYH","International Relations");
		departments.put("FGCY","Introduction to the Humanities Program");
		departments.put("TEDA","Emmett Interdisciplinary Program in Environment and Resources");
		departments.put("QNST","Taube Center for Jewish Studies");
		departments.put("PSJJ","Language Center");
		departments.put("QUZF","Center for Latin American Studies");
		departments.put("PHHL","Linguistics");
		departments.put("SJGK","Management Science and Engineering");
    departments.put("SJ","Management Science and Engineering");
    departments.put("SK","Management Science and Engineering");
		departments.put("QVTK","The Martin Luther King, Jr., Research and Education Institute");
		departments.put("SOWO","Materials Science and Engineering");
		departments.put("QVMR","Math and Computational Science");
		departments.put("JSBG","Math and Computer Science Library");
		departments.put("QDQG","Mathematics");
		departments.put("SRGC","Mechanical Engineering");
    departments.put("SR","Mechanical Engineering");
    departments.put("SS","Mechanical Engineering");
		departments.put("QRFM","Center on Medieval and Early Modern Studies (CMEMS)");
		departments.put("QSXJ","Modern Thought and Literature");
		departments.put("PIEE","Music");
    departments.put("PI","Music");
		departments.put("JPEF","Music Library");
		departments.put("ABMM","University Communications/News Service");
    departments.put("AB","University Communications/News Service");
		departments.put("PJIM","Philosophy");
		departments.put("QDXM","Physics Department");
    departments.put("QE","Physics Department");
		departments.put("JSKQ","Physics Library");
		departments.put("PWTA","Political Science");
		departments.put("FGPP","Program in Writing and Rhetoric");
		departments.put("PXIE","Psychology");
		departments.put("QWGW","Public Policy");
		departments.put("PJXQ","Religious Studies");
		departments.put("QWUI","Science, Technology and Society");
		departments.put("PRFB","Slavic Languages and Literatures");
		departments.put("QXHU","Social Science History Institute");
		departments.put("PYEX","Sociology");
		departments.put("JAAA","Stanford University Libraries");
    departments.put("J","Stanford University Libraries");
		departments.put("QGMH","Statistics");
		departments.put("QYIS","Symbolic Systems");
		departments.put("QYWE","Urban Studies");

		return departments;
	}
}
