#!/bin/bash

. /s/SUL/Config/sirsi.env

HOME=/s/SUL/Harvester
LOG=$HOME/log
OUT=$HOME/out
DATE=$1

if [ -z $DATE ]
then
  DATE=`date +%Y%m%d%H%M`
fi

for F in `ls $OUT/course_harvest.out*`
do
	OUTFile="$OUTFile $F"
done
	
cd $HOME/classes/course

echo "Running: java -cp .:../../lib/jdom-2.0.6.jar BuildCourseXML $OUTFile"

java -cp .:../../lib/jdom-2.0.6.jar BuildCourseXML $OUTFile

cat $LOG/course-build.log | mailx -s 'Course Build Log' sul-unicorn-devs@lists.stanford.edu
mv $LOG/course-build.log $LOG/course_build.log.$DATE
touch $LOG/course-build.log

