#!/bin/bash

. /s/SUL/Config/sirsi.env

HOME=/s/SUL/Harvester
LOG=$HOME/log
uLOG=$HOME/include/courses
OUT=$HOME/out
JVM1=$1
JVM2=$2
OUTFile=$3
DATE=`date +%Y%m%d%H%M`

if [ -z $JVM1 ]
then
  JVM1="2G"
fi

if [ -z $JVM2 ]
then
  JVM2="10G"
fi

if [ "$OUTFile" == "latest" ]
then
  OUTFile = `ls $OUT/course_harvest.out* | tail -1`
elif [ -z $OUTFile ]
then
  for F in `ls $OUT/course_harvest.out*`
  do
    OUTFile="$OUTFile $F"
  done
fi

cd $HOME/classes/course

echo "Running: java -Xms${JVM1} -Xmx${JVM2} -cp .:../../lib/jdom-2.0.6.jar BuildCourseXML $OUTFile"

java -Xms${JVM1} -Xmx${JVM2} -cp .:../../lib/jdom-2.0.6.jar BuildCourseXML $OUTFile

cat $LOG/course-build.log | mailx -s 'Course Build Log' sul-unicorn-devs@lists.stanford.edu
mv $LOG/course-build.log $LOG/course_build.log.$DATE
mv $uLOG/updates.log $uLOG/updates.log.$DATE
touch $LOG/course_build.log
touch $LOG/course-build.log
