#!/bin/bash

. /s/SUL/Config/sirsi.env

HOME=/s/SUL/Harvester
LOG=$HOME/log
OUT=$HOME/out
DATE=$2
COURSE_IDS=$1

if [ -z $DATE ]
then
  DATE=`date +%Y%m%d%H%M`
fi

$HOME/run/course_fileLoad.sh $COURSE_IDS

cat $LOG/course_harvest.log | mailx -s 'Course Harvest Log' sul-unicorn-devs@lists.stanford.edu

mv $LOG/course_harvest.log $LOG/course_harvest.log.$DATE
mv $OUT/course_harvest.out $OUT/course_harvest.out.$DATE

touch $LOG/course_harvest.log

usage(){
    echo "Usage: $0 [ File of COURSE_IDs ] [ DATE (to append to log and out file when finished) ]"
    exit 1
}

[[ $# -lt 1 ]] && usage
