#!/bin/bash

HOME=/s/SUL/Harvester
LOG=$HOME/log
OUT=$HOME/out
DATE=$1

if [ -z $DATE ]
then
    DATE=`date +%Y%m%d`
fi

$HOME/run/runonce.sh
$HOME/run/usertrans $DATE

perl -p -i -e 's/\r//g' $LOG/harvest.log

cat $LOG/harvest.log | mailx -s 'Harvest Log' sul-unicorn-devs@lists.stanford.edu

$HOME/run/pop2illiad 

mv $LOG/harvest.log $LOG/harvest.log.$DATE
mv $OUT/harvest.out $OUT/harvest.out.$DATE
mv $LOG/illiad.log $LOG/illiad.log.$DATE

touch $LOG/harvest.log
touch $LOG/illiad.log
