#!/bin/bash

. /s/SUL/Config/sirsi.env

HOME=/s/SUL/Harvester/current
LOG=$HOME/log
OUT=$HOME/out
DATE=$2
KEYS=$1

if [ -z $DATE ]
then
  DATE=`date +%Y%m%d%H%M`
fi

# Run the registry harvest
$HOME/run/fileLoad.sh $KEYS

# Fix up the harvest.out files
$HOME/run/usertrans $DATE

mv $LOG/harvest.log $LOG/harvest.file.log.$DATE
mv $OUT/harvest.out $OUT/harvest.file.out.$DATE

usage(){
    echo "Usage: $0 [ File of KEYS ] [ DATE (to append to log and out file when finished) ]"
    exit 1
}

[[ $# -lt 1 ]] && usage
