#!/bin/bash

. /s/SUL/Config/sirsi.env

HOME=/s/SUL/Harvester
LOG=$HOME/log
OUT=$HOME/out
DATE=$1

if [ -z $DATE ]
then
    DATE=`date +%Y%m%d`
fi

$HOME/run/runonce.sh
$HOME/run/usertrans $DATE

perl -p -i -e 's/\r//g' $LOG/harvest.log

# yesterday...
illiad_date=`/s/sirsi/Unicorn/Bin/transdate -d-1 | cut -c5-`
$HOME/run/pop2illiad $illiad_date

cat $LOG/harvest.log | mailx -s 'Harvest Log' sul-unicorn-devs@lists.stanford.edu

if [ -e $LOG/harvest.log.$DATE ]
  then
  mv $LOG/harvest.log $LOG/harvest.log.`date +%Y%m%d%H%M`
else
  mv $LOG/harvest.log $LOG/harvest.log.$DATE
fi
mv $OUT/harvest.out $OUT/harvest.out.$DATE

if [ -e $LOG/illiad.log.$illiad_date ]
  then
  mv $LOG/illiad.log $LOG/illiad.log.${illiad_date}_`date +%H%M`
else
  mv $LOG/illiad.log $LOG/illiad.log.$illiad_date
fi

touch $LOG/harvest.log
touch $LOG/illiad.log
