#!/bin/bash

. /s/SUL/Config/sirsi.env

HOME=/s/SUL/Harvester/current
LOG=$HOME/log
OUT=$HOME/out
DATE=$1

if [ -z $DATE ]
then
  DATE=`date +%Y%m%d%H%M`
fi

# Run the registry harvest
$HOME/run/runonce.sh

# Fix up the harvest.out files
$HOME/run/usertrans $DATE

mv $LOG/harvest.log $LOG/harvest.log.$DATE
mv $OUT/harvest.out $OUT/harvest.out.$DATE
