#!/bin/bash

HOME="/s/SUL/Harvester"
LOG="$HOME/log"
DATE=$1

cd $HOME/classes

echo "Processing /s/SUL/Batchlog/userload.keys.$DATE for ILLiad" > $LOG/illiad.log
echo ""
java -cp .:../lib/commons-io-2.4.jar:../lib/ojdbc14.jar:../lib/sqljdbc4.jar Pop2ILLiad /s/SUL/Batchlog/userload.keys.$DATE > $LOG/illiad.log  2>&1




