#!/bin/bash

HOME="/s/SUL/Harvester"
LOG="$HOME/log"
DATE=$1

KEY_DIR="/s/SUL/Batchlog"
KEY_FILE="$KEY_DIR/userload.keys.$DATE"

if [ $(grep -c "^[0-9]\+" $KEY_FILE) -gt 10000 ]
then
  cd $KEY_DIR
  split -a 1 -l 5000 $KEY_FILE "userload.keys.$DATE."

  cd $HOME/lib

  for FILE in `find $KEY_FILE.*`
  do
    echo "Processing $FILE for ILLiad" > $LOG/illiad.log
    echo "" >> $LOG/illiad.log
    cat $FILE | sort | uniq > ${FILE}_uniq

    java -jar PersonToILLiad-jar-with-dependencies.jar edu.stanford.Pop2ILLiad ${FILE}_uniq keyfile >> $LOG/illiad.log  2>&1
  done
else
  cd $HOME/classes

  echo "Processing $KEY_FILE for ILLiad" > $LOG/illiad.log
  echo "" >> $LOG/illiad.log
  cat $KEY_FILE $KEY_FILE.3 | sort | uniq > ${KEY_FILE}_uniq

  java -jar PersonToILLiad-jar-with-dependencies.jar edu.stanford.Pop2ILLiad ${KEY_FILE}_uniq keyfile >> $LOG/illiad.log  2>&1
fi

if [ -z $(grep "Error" $LOG/illiad.log) ]
then
    VALUES=`grep "VALUES" $LOG/illiad.log | wc -l`
    echo "" >> $LOG/illiad.log
    echo "$VALUES rows inserted into ILLiad Users Table" >> $LOG/illiad.log
fi

cat $LOG/illiad.log | mailx -s 'ILLiad User Export Log' sul-unicorn-devs@lists.stanford.edu
rm $KEY_DIR/userload.keys.*_uniq
