#!/bin/bash

HOME="/s/SUL/Harvester"
LOG="$HOME/log"

cd $HOME/classes/course 

for F in `ls ../../out/course_harvest*`
do 
  FILES="$FILES $F"
done

echo "java -cp .:../../lib/jdom-1.0.6.jar BuildCourseXML $FILES"


